# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            vchrombie
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://vchrombie.github.io
baseurl:          /blog

disqus_shortname: vchrombie

author:
  name:           'Venu'
  url:            https://vchrombie.github.io/

paginate:         10

plugins:          [jekyll-paginate]


# Custom vars
appname:          blog
version:          2.1.0

github:
  repo:           https://github.com/vchrombie/blog/
